export const pages = {
  home: {
    title: "Home",
    description: "Main brand landing page",
    sections: [
      "Hero introduction",
      "Value proposition",
      "Talent / Host opportunity",
      "Agent opportunity",
      "Services overview",
      "Platform partnerships",
      "Statistics / achievements",
      "Why Streamintia",
      "How it works",
      "Testimonials",
      "Collaboration CTA",
      "Final CTA",
    ],
  },
  about: {
    title: "About Us",
    description: "Who Streamintia is",
    sections: [
      "About Streamintia",
      "Mission",
      "Vision",
      "What we do",
      "Our approach",
      "Why creators choose us",
      "Why agents choose us",
      "Global vision",
      "Trust / credibility",
      "CTA",
    ],
  },
  services: {
    title: "Services",
    description: "Recruitment, management and creator support",
    sections: ["Services overview"],
  },
  "become-streamer": {
    title: "Become a Streamer",
    description: "Explore live-streaming host opportunities",
    sections: [
      "Why become a streamer",
      "Benefits",
      "How streaming works",
      "What Streamintia provides",
      "Requirements",
      "Supported platforms",
      "Earning opportunity explanation",
      "Step-by-step joining process",
      "FAQ preview",
      "Apply CTA",
    ],
  },
  "become-agent": {
    title: "Become an Agent",
    description: "Explore talent agent opportunities",
    sections: [
      "What an agent does",
      "Benefits",
      "How agents earn",
      "Recruiting hosts",
      "Managing talent",
      "Support from Streamintia",
      "Growth opportunity",
      "Requirements",
      "Step-by-step process",
      "Apply CTA",
    ],
  },
  platforms: {
    title: "Our Platforms",
    description: "Platform directory and application pathways",
    sections: [
      "Platform introduction",
      "Platform details",
      "Host CTA",
      "Agent CTA",
    ],
  },
  "how-it-works": {
    title: "How It Works",
    description: "The journey from application to growth",
    sections: ["Host journey", "Agent journey"],
  },
  "why-streamintia": {
    title: "Why Streamintia",
    description: "Our approach to creator and agent support",
    sections: [
      "Professional guidance",
      "Multiple platform opportunities",
      "Creator support",
      "Agent support",
      "Training",
      "Growth guidance",
      "Dedicated assistance",
      "Global opportunities",
      "Transparent process",
      "Long-term creator relationships",
    ],
  },
  "success-stories": {
    title: "Success Stories",
    description: "Approved creator and agent stories",
    sections: [
      "Testimonials",
      "Creator stories",
      "Agent stories",
      "Results / achievements",
      "Case studies",
      "CTA",
    ],
  },
  contact: {
    title: "Contact Us",
    description: "Business and partnership enquiries",
    sections: [
      "Email",
      "WhatsApp",
      "Office / location",
      "Business enquiry",
      "Partnership enquiry",
      "Social links",
    ],
  },
  apply: {
    title: "Apply Now",
    description: "Choose a role and platform",
    sections: ["Application introduction", "Contact alternative"],
  },
  "privacy-policy": {
    title: "Privacy Policy",
    description: "Privacy information for visitors and applicants",
    sections: [
      "Information collected",
      "Purpose of processing",
      "Sharing and retention",
      "Your choices",
      "Contact",
    ],
  },
  "terms-and-conditions": {
    title: "Terms and Conditions",
    description: "Terms for using Streamintia",
    sections: [
      "Website use",
      "Applications and eligibility",
      "Platform relationships",
      "Earnings and responsibilities",
      "Contact",
    ],
  },
} as const;
export type PageKey = keyof typeof pages;
export const routeFor = (key: PageKey) => (key === "home" ? "/" : `/${key}`);
